spring.application.name=Backend-Chat

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://vikkykumargupta7667_db_user:sOXV1m2wOvLTBS0X@chat-room.66aodre.mongodb.net/?appName=chat-room

# Increase upload limits (e.g., 50MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# If storing locally, map the URL to the physical folder
spring.web.resources.static-locations=file:uploads/

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=chat-media